### ISSUE TITLE
There is no settings page

### ISSUE THREAD

**Issue by bartrylant** [balazscsaba2006/craft3-cookiebot#1]
When I go to settings > plugins, cookiebot is listed and installed, but there is no button to change the settings.

Cookiebot | 1.0.3
Craft edition & version | Craft Pro 3.0.10.3

**Comment by balazscsaba2006** [comment]
Thanks @bartrylant for signaling this, fixed in latest release, [1.0.4](https://github.com/balazscsaba2006/craft3-cookiebot/releases/tag/1.0.4).
