### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by arifje** [balazscsaba2006/craft3-cookiebot#2]
![screen shot 2018-07-06 at 15 23 41](https://user-images.githubusercontent.com/1286410/42381207-adb02040-8130-11e8-8925-834c211cb1c0.jpg)

Craft CMS 3.0.14

**Comment by balazscsaba2006** [comment]
@skoften What version of PHP are you using? Void return type was introduced in `7.1`, [RFC here](https://wiki.php.net/rfc/void_return_type)

**Comment by balazscsaba2006** [comment]
Fixed in https://github.com/balazscsaba2006/craft3-cookiebot/releases/tag/1.0.6

**Comment by arifje** [comment]
great, thnx

FYI, I am running PHP 7.0.30
