### ISSUE TITLE
Craft 4 version

### ISSUE THREAD

**Issue by bencroker** [balazscsaba2006/craft3-cookiebot#7]
Hi there, do you plan on releasing a Craft 4 compatible version any time soon? Since I have a site using this plugin that I'd like to update to Craft 4, it would be much appreciated.

**Comment by xswirelab** [comment]
What makes it incompatible?

**Comment by bencroker** [comment]
This line, for one... https://github.com/balazscsaba2006/craft3-cookiebot/blob/aedbe444fdb897c8cc34f4d4c5313180de2f9d24/composer.json#L29

**Comment by xswirelab** [comment]
Ah so it's just the version that needs to be upped?

@bencroker have you tested the workings after upping the version? We could add a pull-request and fix it easy.

**Comment by xswirelab** [comment]
@bencroker I've forked and added Craft4 compatibility. Could you be so friendly and see if it works?
I've tested it on a fresh craft 4 install and didnt get any problems myself.
The following need to be added to your composer.json.

The require node need the dev-craftxswirelab(my fork)

```json
  "require": {
    "craftcms/cms": "^4.0.0.1",
    "balazscsaba2006/cookiebot": "dev-craft4xswirelab"
  },
```
Add minimum stability, but prefer stable:

```json
  "minimum-stability": "dev",
  "prefer-stable": true,
```

Add the fork's repo, so packagist won't look somewhere else:

```json
  "repositories": [{
    "type": "vcs",
    "url": "https://github.com/xswirelab/craft3-cookiebot"
  }],
```

**Full example composer.json on a fresh craft cms 4 install**

```json
{
  "require": {
    "craftcms/cms": "^4.0.0.1",
    "vlucas/phpdotenv": "^5.4.0",
    "balazscsaba2006/cookiebot": "dev-craft4xswirelab"
  },
  "require-dev": {
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": [{
    "type": "vcs",
    "url": "https://github.com/xswirelab/craft3-cookiebot"
  }],
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.0.2"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

**Comment by balazscsaba2006** [comment]
Thanks @xswirelab for the PR and @bencroker for raising the issue. I've release v2.0.0 that is compatible with Craft4 and PHP 8.0+

**Comment by xswirelab** [comment]
> Thanks @xswirelab for the PR and @bencroker for raising the issue. I've release v2.0.0 that is compatible with Craft4 and PHP 8.0+

Awesome. 
Thank you for merging 💪
